# Generated by Django 4.0.4 on 2022-05-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
